name: Atkins Park
favicon: null
layout_spectrum: 0.36559515027329326
typography_spectrum: 0.5981260603293777
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.09623732860200107
  lightness: 0.32095546601340175
  saturation: 0.815724328160286
  rhythmicContrast: 0.512765234336257
purpose: []
