name: Atkins Park
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25168
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7c6d68'
    - '#b09d8e'
    - '#d9cbc0'
    - '#53443f'
    - '#070406'
  brandStrength: 0.5
  lightness: 0.32095546601340175
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
